### ISSUE TITLE
Create checklist of things that this package will and won't do

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/motCarData#1]
After conversations with @mem48 and @wengraf it seems that a package will be useful for this. This is a placeholder for that package. So far I think the following functions should be included:

- [ ] Functions to get data from the API, e.g. `mot_get()`?
- [ ] Functions to download data, `mot_dl()?
- [ ] Functions to process the data, `mot_format_*()`?

Thoughts very welcome.

**Comment by mem48** [comment]
There are several apis so perhapse more than 1 function needed. Also help with batch dowloads may be useful.

**Comment by wengraf** [comment]
Good point @mem48.  I've got a parallelized bit of code for bulk download (8 CPUs is the functional max, and the progress bar is a blessing), and I'm playing around with some code for a safety specific output with derived variables - I'm currently working on making sure it handles cherished plates the best way it can (use the VRM to find the VehicleID so you get the full vehicle history of whatever vehicle currently has that plate at the time of the API call).

**Comment by wengraf** [comment]
But I see that you could have something like mot_dl_VRM() with a list of VRMs as inputs, with the results as a list in the last column, then use something like mot_format_safety() to make a flat, road safety focused table.

**Comment by wengraf** [comment]
@mem48 and @Robinlovelace : I've have a play around.  I guess my questions are basically around workflow.

1. The functions so far only deal with the pages endpoint.  I would imagine a two use cases for this endpoint - one where you download the lot, and another where you download the most recent and add it to existing locally stored data.  Function names etc. would need to suggest that.  I think the VRM endpoint is next in terms of interest to analysts, and the other two are much more for the trade (so would be last in terms of priority).

2. This code so far creates a third vehicle ID variable ("id") alongside number plate and Vehicle ID.  Is this too much?  The order of the vehicles on the pages of the API are basically random (or, rather, ordered by a variable that isn't given in the API), so stick with the others instead?

3. I like the test and main outputs, but would you ever want the test results without the main data linked to it?  In other words, should the function allow for a choice: "main", which gets you an output where each row is a vehicle, and "test" where each row is a vehicle _and_ each test.

4. I'm not familiar with your method of API access, but it looks neat.  How does it handle API versions, and should this be prepare for any further updates (given that the updates have been fairly frequent so far)?

5. Are the colours and fuel types you list as potential factors complete, or only what you've found so far?  How would it handle an as-yet-unused colour?

6. Similarly, how would it handle an NA for odometer unit?

7. I've been told that the pages API has gaps.  So if you want to get the entire set you need to keep going past the first blank page.  Currently circa 128000.

**Comment by mem48** [comment]
@wengraf 

Sorry fro slow reply

1. Fair point, I think the package should cover all endpoints they are all quite similar so their should be plenty of shared code.

2. The extra ID is their becuase some cars share VRMs, this screwed over my inital analysis and I had to re-download the data as their was no way to retroactivly identify the duplicates.

3. Intresting idea, but I would suggest that ti would be bettter to have a function to change the format of already downloaded data, as it would reduce API usage. 

4. The httr package is mature and does msot things, I like it because it makes API work very easy, api version would just be added as an aditonal parameter.

5. They are complete from mut total download last month. THis may not be the best solution for the package. Becuase they you add another colour at any time. The problem I was solving is that binding mulitple factors togther with different levles coreses to character lossing the significant memoery savings. 

6. Yes, factors support NA

7. Thanks I did not know that.
